MyImdb/Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;
using MyImdb.Models;
using MyImdb.Services;
using MyImdb.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyImdb.Controllers
{
    public class MovieController : Controller
    {
		private readonly ViewModelConverter vmc;

		public MovieController(ViewModelConverter vmc) {
			this.vmc = vmc;
		}

        public IActionResult Index(string msg = null){
			var movies = vmc.ToMovieList(Movie.SelectAll());
			ViewBag.Message = msg;
			// Outras formas:
			// tupla
			// novo ViewModel
			// ViewData
            return View(movies);
        }

		public IActionResult MovieInfo(int id) {
			var movie = Movie.SelectAll().FirstOrDefault(m => m.Id == id);
			if (movie == default(Movie)) {
				return RedirectToAction(nameof(HomeController.Error), "Home", new { message = $"Movie id={id} not found!"});
			}

			ViewData["ContentTitle"] = TempData["ContentTitle"];
			return View(vmc.ToMovieInfo(movie));
		}

        public IActionResult MovieOfTheMonth(){
			var movieOfTheMonth = Movie.SelectAll().FirstOrDefault(m => m.Year == DateTime.Now.Year);
			TempData["ContentTitle"] = "Movie of The Month";
            return RedirectToAction(nameof(MovieInfo), new { id = movieOfTheMonth.Id });
        }

		
		public IActionResult Create() {
			return View();
		}

		[HttpPost]
		public	IActionResult Create(MovieCreateViewModel model) {
			if (!ModelState.IsValid) {
				return View(model);
			}
			return RedirectToAction(nameof(Index), new { msg = "Movie created with success." });
		}
	}
}

MyImdb/Views/Shared/Navbar.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
	<div class="container">
		<a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">MyImdb</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
				aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
			<ul class="navbar-nav flex-grow-1 row">
				<li class="nav-item col-1">
					<a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
				</li>
				<li class="nav-item col-1">
					<a class="nav-link text-light" asp-area="" asp-controller="Movie" asp-action="Index">Movie</a>
				</li>
				<li class="nav-item col-2 offset-8">
					<input type="text" class="form-control" placeholder="Search Movie" />
				</li>
			</ul>
		</div>
	</div>
</nav>

MyImdb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyImdb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("head", required: false)
</head>
<body>
    <header>
        <partial name="Navbar" />
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MyImdb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <partial name="_ValidationScriptsPartial" />
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>